### ISSUE TITLE
Can't configure mod

### ISSUE THREAD

**Issue by LowellaAskew** [pearxteam/Teleporto#1]
When I open Minecraft and go to the mods menu the configure option is greyed out making me unable to do so. I'm using Forge 1.12.1 and Teleporto version 1.0.3.

**Comment by mrapplexz** [comment]
Configure the mod using any text editor in the .cfg file located in the "<your minecraft directory>/config" directory. Maybe, I'll add the GUI config screen one day.

**Comment by LowellaAskew** [comment]
Alright, thanks. :)
